# This is a basic workflow to help you get started with Actions

name: Feynman - linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install
        run: |
          pip install pandas
          pip install sklearn
          pip install sympy
          pip install .

      - name: Run test
        run: |
          python3 ./ci-test/test.py --dataset feynman
          git pull
          mv -f ./ci-test/results/feynman.csv ./ci-test/results/feynman_linux.csv

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: "./ci-test/results/feynman_linux.csv"
