name: Feynman - linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install
        run: |
          pip install pandas
          pip install scikit-learn
          pip install sympy
          pip install .

      - name: Run test
        run: |
          python3 ./ci-test/test.py --dataset feynman
          git pull
          mv -f ./ci-test/results/feynman.csv ./ci-test/results/feynman_linux.csv

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.0
        with:
          add: "./ci-test/results/feynman_linux.csv"
